#!/bin/bash

TS=$(date "+%Y-%m-%d %H:%M:%S")
ID=$1
NICKNAME=$(grep $ID name.list | cut -d' ' -f2)

if  [[ "" == "$NICKNAME" ]]
then
    NICKNAME="lady"
fi

echo "[$TS] hello $NICKNAME"  # 等价于 echo [$TS] hello $NICKNAME

